### ISSUE TITLE
"toLowerCase" from null error when using the filter for custom model.

### ISSUE THREAD

**Issue by azaharizaman** [ITDSystems/alvex-datagrid#1]
When filtering through a 1000+ datalist items, I got this error;

<code>10100004 Wrapped Exception (with status template): 10100142 Failed to execute script 'classpath*:alfresco/extension/templates/webscripts/alvex/datalists/datalist-search.post.json.js': 10100141 TypeError: Cannot read property "toLowerCase" from null (file:/C:/Alfresco/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/templates/webscripts/alvex/datalists/datalist-search.post.json.js#591)</code>

It was okay before i started to put in many items in the datalist, and now the data list is too big, I got this error everytime.

Regards,
Azahari

**Comment by douglascrp** [comment]
Just make sure the variable you are trying to make lower case is not null before executing the method.
Something like

if (variable != null) {
   variable.toLowerCase()
}
