### ISSUE TITLE
Access To Registers

### ISSUE THREAD

**Issue by Funies** [ITDSystems/alvex-datagrid#16]
Hi,

The previous version of Alvex, the one compatible with Alfresco version 4.2 had an office site option which is where we could access all Alvex related registers.
On the new version I am not sure where to access the registers as there is no Office Site option any more.
On Admin tools screen on Alfresco I have the following options under Alvex:
Master Data, Org Chart, Project Sites and workflow Permission.

My environment is as follows: Alfresco Version is 5.1.f and Alvex is: alvex-3.0-20161010.110655-51.
I deployed all the jars in that zip file.

Kind Regards

**Comment by aviriel** [comment]
Document Registers are not ported to Alfresco 5.1 yet. It will be another component after we rework its architecture and UI.
