### ISSUE TITLE
Datagrid Edit redirecting to another page and not working

### ISSUE THREAD

**Issue by errmerrged** [ITDSystems/alvex-datagrid#17]
Hello, I am using the Alvex build last January 7,2017 from http://nexus.itdhq.com/index.html#view-repositories;public~browsestorage~/com/alvexcore/alvex/3.0-SNAPSHOT/alvex-3.0-20170419.123059-228.zip . It is partially working but after hitting **Edit** button to the item, it redirects to another page instead of the pop-up and still edit doesn't work. Cheers

**Comment by lmaorence** [comment]
Edit this file:
documents-register-datagrid.get.config.xml
