### ISSUE TITLE
Переход от последней community на компоненты

### ISSUE THREAD

**Issue by akurutin** [ITDSystems/alvex-datagrid#18]
Подскажите пожалуйста, стояла community версия алвекса, я создал на основе ваших реестров свой(как описано в курсах). Создал модель, загрузил ее в контексте

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE beans PUBLIC '-//SPRING//DTD BEAN//EN' 'http://www.springframework.org/dtd/spring-beans.dtd'>
<beans>
	<bean id="gk21-documents" parent="dictionaryModelBootstrap" depends-on="dictionaryBootstrap,alvex-documents-registers-deployer">
		<property name="labels">
			<list>
				<value>alfresco.extension.messages.gk21-documents</value>
                <value>alfresco.extension.messages.gk21-counteragent</value>
			</list>
		</property>
		<property name="models">
			<list>
				<value>alfresco/extension/models/gk21-documents-model.xml</value>
			</list>
		</property>
	</bean>
</beans>
```
Потом удалил все jar файлы от комьюнити и добавил все компоненты от alvex3. После чего мне лог файл говорит, что не может найти alvex-deployer:

> org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'alvex-documents-registers-deployer' is defined

В компонентах что то изменилось?

**Comment by aviriel** [comment]
Сейчас на Alfresco 5 нет реестров. Так что родителя Ваших кастомных реестров нет в системе.
