### ISSUE TITLE
The New Item button is enabled, but does nothing when clicked

### ISSUE THREAD

**Issue by douglascrp** [ITDSystems/alvex-datagrid#25]
I saw the issue #9 got fixed, but now, even though the button is enabled, nothing happens when it is clicked.

**Comment by aviriel** [comment]
Fixed this, but now it opens the dialog twice (newRow fucntion is called twice for some reason), will think about it later

**Comment by douglascrp** [comment]
Yes, it is annoying, but it works.

**Comment by aviriel** [comment]
Created #26 and #27. Close this issue as fixed
