### ISSUE TITLE
New item button click opens dialog twice

### ISSUE THREAD

**Issue by aviriel** [ITDSystems/alvex-datagrid#26]

**Comment by douglascrp** [comment]
@aviriel Are you going to work on this soon?
I you aren't, then I will work on it.
I am asking this just to avoid having two of us working on the same issue.
If you have any idea on what can be the reason for this, then please, let me know.

**Comment by aviriel** [comment]
I tried to solve it yesterday, but didn't succeed. So I was going to leave it till one of our developers who wrote this code and know YUI2 will take a look at it. But if you think that you can solve it, please do it :)

It looks like all datagrid functions are called twice. Also we can see 2 requests to get the form from repo. In the same way on My tasks page the search toolbar is opened twice (2 buttons on it) and requests for the list of tasks is sent twice. Maybe we doubled something while migrating datagrid. But I have no idea what.
