### ISSUE TITLE
Question is still compatibile with the 4.2.X version of alfresco?

### ISSUE THREAD

**Issue by p4535992** [ITDSystems/alvex-datagrid#28]
Is still compatibile with the 4.2.X version of alfresco?

**Comment by aviriel** [comment]
no, as far as now it requires masterdata extension be installed, and it's only for Alfresco 5. If you need it for Alfresco 4.2, take old version from the repo by reverting last commits. Llike this: https://github.com/ITDSystems/alvex-datagrid/tree/3d3777469fbf3f41f87a485d3c8a534ae507794c
