### ISSUE TITLE
Cyclic dependency between datagrid repo and master data repo

### ISSUE THREAD

**Issue by hoangbktech** [ITDSystems/alvex-datagrid#30]
There is a cyclic dependency between datagrid repo and master data repo when looking at their pom file, please take a look at it and check if this is a bug.

**Comment by aviriel** [comment]
Hi! It's a known problem. Actually it's not a bug. Masterdata extension requires datagrid to show datalist columns on the masterdata administration page. Datagrid extension requires masterdata to render allowed values in LIST-constraints in the search row above datagrid.
We will take a look at this problem after Alvex 3.0 final release. As for now it's not a bug and you can use it.
