### ISSUE TITLE
alvex/datalists/list-all-available.get.json.ftl"

### ISSUE THREAD

**Issue by shin0bi2014** [ITDSystems/alvex-datagrid#31]
Поставил alvex-datagrid и предположительные зависимости, может конечно что-то упустил. Все работает без ошибок, но когда захожу в Инструменты администратора. Открываю вкладку Alvex Управление справочниками возникают вот эти все ошибки.
```
`Caused by: org.alfresco.service.cmr.repository.TemplateException: 10160087 Ошибка во время обработки шаблона 'The following has evaluated to null or missing:
==> jsonUtils.encodeJSONString(x)  [in template "alvex/datalists/list-all-available.get.json.ftl" at line 1, column 15]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction:
==> ${dl.listTitle} auto-escaped  [in template "alvex/datalists/list-all-available.get.json.ftl" at line 9, column 39]'. Обратитесь к системному администратору.
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:227)
        at org.springframework.extensions.webscripts.AbstractWebScript.renderTemplate(AbstractWebScript.java:967)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.renderFormatTemplate(DeclarativeWebScript.java:267)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:147)
        ... 32 more
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> jsonUtils.encodeJSONString(x)  [in template "alvex/datalists/list-all-available.get.json.ftl" at line 1, column 15]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction:
==> ${dl.listTitle} auto-escaped  [in template "alvex/datalists/list-all-available.get.json.ftl" at line 9, column 39]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:382)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:193)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:509)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.EscapeBlock.accept(EscapeBlock.java:85)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:223)
        ... 35 more
`
```
Если в данный раздел не заходить, то все работает нормально  и ошибок не выдает.
Верси Alfresco 5.1.f
Возможно alvex datagrid настроить только на определенный сайт или даталист, а не на все сразу?
Заранее благодарю !

**Comment by aviriel** [comment]
Какие именно компоненты стоят? Можете прислать листинг jar-ников в системе, содержащих слово "alvex"? Страница справочников и потерянный ftl являются частью alvex-masterdata, а не datagrid.
Нет, поставить datagrid на один сайт нельзя.

**Comment by shin0bi2014** [comment]
листинг repo:
![repo](https://user-images.githubusercontent.com/8466842/32913767-605041a8-cb24-11e7-87c9-40b173bf4be5.png)

листинг share:
![share](https://user-images.githubusercontent.com/8466842/32913783-6f888996-cb24-11e7-9b76-9e1e700e842f.png)

кнопка "очистить"для интервала дат не работает, сколько не пробовал жать не очищает, min max крайне странно работает, выдает случайные интервалы, скорей относится в кнопке max.
![date](https://user-images.githubusercontent.com/8466842/32930352-532d12d0-cb6f-11e7-87b5-20216b844c7b.png)
скорей может это связанно?

**Comment by shin0bi2014** [comment]
кажется нашел, по какой то причине полностью не установились файлы из alvexcore.repo.masterdata, а поставились наполовину. К сожалению переустановка яр файлов и заливка в ручную папок с шаблонами не помогла :(
Продолжаются сыпаться ошибки

```
FreeMarker template error:
The following has evaluated to null or missing:
==> jsonUtils.encodeJSONString(x)  [in template "alvex/datalists/list-all-available.get.json.ftl" at line 1, column 15]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction (FTL stack trace):
----------
==> ${dl.listTitle} auto-escaped  [in template "alvex/datalists/list-all-available.get.json.ftl" at line 9, column 39]
----------

Java stack trace (for programmers):
----------
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
 
```

**Comment by aviriel** [comment]
Проверили. На 5.2.f правда, а не 5.1.f, так как старые релизы уже непонятно где скачивать, там как раз wiki alfresco переезжала, и старые страницы со ссылками потерялись.
При копировании перечисленных Вами выше файлов в modules/platform и modules/share проблема с шаблоном не воспроизводится. В поиске в datagrid - да, не работает кнопка очистки, это исправим, но страница управления справочниками отлично открывается.
![screenshot from 2017-11-18 00-37-39](https://user-images.githubusercontent.com/596948/32970168-e57067a8-cbf8-11e7-958c-3c44c8b6fcfc.png)
Может не туда скопированы jar-ники? Или у меня нет идей, в чем проблема.
Закрываю как невоспроизводящееся.

**Comment by shin0bi2014** [comment]
Скопировал все туда иначе бы не работало, справочник открывается, но при этом сыпит ошибки, как только нажимаю кнопку управления справочниками.
![template](https://user-images.githubusercontent.com/8466842/32978349-88e9f054-cc51-11e7-9cad-c62c78e556aa.png)

если проблема именно с версией 5.1, испытаю на 5,2  может и правда пора переходить на 5,2 )
Спасибо буду тестить на 5,2 и отпишусь.

**Comment by aviriel** [comment]
С этим тоже проблем не наблюдается. Возможно, все-таки 5.1.
![screenshot from 2017-11-18 13-02-24](https://user-images.githubusercontent.com/596948/32979152-1746f522-cc61-11e7-9d2f-5b48374fe3b8.png)
