### ISSUE TITLE
The new item button on any datalist is disabled

### ISSUE THREAD

**Issue by osavigne** [ITDSystems/alvex-datagrid#33]
I´ve an issue with 5.2 version and built from today sources, please help me how can i fix that, the new item button on any datalist is disabled after install this extension

**Comment by aviriel** [comment]
How can we reproduce the issue? We don't see this bug in our environment. Alfresco exact version? Browser version? What Alvex extensions are installed? What other extensions are installed?

**Comment by osavigne** [comment]
i have alfresco community edition version 5.2, no others extensions, and
using firefox 54 and 55

2018-02-10 2:26 GMT-05:00 Oksana Kurysheva <notifications@github.com>:

**Comment by aviriel** [comment]
You didn't answer all my questions. I tested current build (utils + masterdata + datagrid) on Alfresco 5.2 (201707) with Firefox 57. Button works, so cannot reproduce.

**Comment by osavigne** [comment]
compiling amp still not work, but with jar work fine, thanks for your guide

2018-02-11 4:26 GMT-05:00 Oksana Kurysheva <notifications@github.com>:
